runtime: nodejs20

handlers:
  # Serve all static files from the root directory
  - url: /(.*)
    static_files: \1
    upload: (.*)

  # Serve index.html for the root path
  - url: /
    static_files: index.html
    upload: index.html
